# Generated by Django 5.2.4 on 2025-08-28 15:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('full_text', models.TextField(verbose_name='Статья')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles_images/', verbose_name='Фото')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
            ],
        ),
    ]
